Feb 23 17:30:44 bundtbot bundtbot[12851]: 2017-02-23T17:30:44.6487950-06:00 [Info]     DiscordGatewayClient:      Sending Heartbeat ? ?
Feb 23 17:30:44 bundtbot bundtbot[12851]: 2017-02-23T17:30:44.6497660-06:00 [Debug]    DiscordGatewayClient:      Sending opcode Heartbeat to gateway...
Feb 23 17:30:44 bundtbot bundtbot[12851]: 2017-02-23T17:30:44.6687630-06:00 [Debug]    ClientWebSocketWrapper:    Sent 23 bytes (ClientWebSocket State: Open)
Feb 23 17:30:44 bundtbot bundtbot[12851]: 2017-02-23T17:30:44.6736090-06:00 [Debug]    DiscordGatewayClient:      Sent Heartbeat
Feb 23 17:30:44 bundtbot bundtbot[12851]: 2017-02-23T17:30:44.7009600-06:00 [Debug]    ClientWebSocketWrapper:    Received 36 bytes on ClientWebSocket(EndOfMessage: True)
Feb 23 17:30:44 bundtbot bundtbot[12851]: 2017-02-23T17:30:44.7024710-06:00 [Debug]    DiscordGatewayClient:      Message received from gateway (opcode: HeartbackAck)
Feb 23 17:30:44 bundtbot bundtbot[12851]: 2017-02-23T17:30:44.7031970-06:00 [Info]     HeartbackAckOperation:     HeartbackAck Received ? ?
Feb 23 17:30:50 bundtbot bundtbot[12851]: 2017-02-23T17:30:50.2693210-06:00 [Warning]  ClientWebSocketWrapper:    Exception caught in ClientWebSocketWrapper ReceiveLoop.
Feb 23 17:30:50 bundtbot bundtbot[12851]: 2017-02-23T17:30:50.2737900-06:00 [**ERROR**]ClientWebSocketWrapper:    System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake.
Feb 23 17:30:50 bundtbot bundtbot[12851]: 2017-02-23T17:30:50.3397530-06:00 [**ERROR**]ClientWebSocketWrapper:       at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__60.MoveNext()
Feb 23 17:30:50 bundtbot bundtbot[12851]:         --- End of stack trace from previous location where exception was thrown ---
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at BundtBot.ClientWebSocketWrapper.<ReceiveAsync>d__16.MoveNext() in C:\Users\Bundt\Source\Repos\BundtBot\src\DiscordApiWrapper\Gateway\ClientWebSocketWrapper.cs:line 129
Feb 23 17:30:50 bundtbot bundtbot[12851]:         --- End of stack trace from previous location where exception was thrown ---
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at BundtBot.ClientWebSocketWrapper.<>c__DisplayClass13_0.<<StartReceiveLoop>b__0>d.MoveNext() in C:\Users\Bundt\Source\Repos\BundtBot\src\DiscordApiWrapper\Gateway\ClientWebSocketWrapper.cs:line 86
Feb 23 17:30:50 bundtbot bundtbot[12851]: 2017-02-23T17:30:50.3457010-06:00 [**ERROR**]ClientWebSocketWrapper:    InnerException1: $System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake.
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__69.MoveNext()
Feb 23 17:30:50 bundtbot bundtbot[12851]:         --- End of stack trace from previous location where exception was thrown ---
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 23 17:30:50 bundtbot bundtbot[12851]:            at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__60.MoveNext()
Feb 23 17:30:50 bundtbot bundtbot[12851]: 2017-02-23T17:30:50.3458650-06:00 [Warning]  ClientWebSocketWrapper:    Waiting for 1 seconds, then restarting ReceiveLoop
Feb 23 17:30:51 bundtbot bundtbot[12851]: 2017-02-23T17:30:51.3462020-06:00 [Warning]  ClientWebSocketWrapper:    Doubled web socket restart wait time to 2 seconds
Feb 23 17:30:51 bundtbot bundtbot[12851]: 2017-02-23T17:30:51.3469540-06:00 [Warning]  ClientWebSocketWrapper:    Restarting ClientWebSocketWrapper ReceiveLoop.
Feb 23 17:30:51 bundtbot bundtbot[12851]: 2017-02-23T17:30:51.3480280-06:00 [Warning]  ClientWebSocketWrapper:    Exception caught in ClientWebSocketWrapper ReceiveLoop.
Feb 23 17:30:51 bundtbot bundtbot[12851]: 2017-02-23T17:30:51.3483540-06:00 [**ERROR**]ClientWebSocketWrapper:    System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake.
Feb 23 17:30:51 bundtbot bundtbot[12851]: 2017-02-23T17:30:51.3496020-06:00 [**ERROR**]ClientWebSocketWrapper:       at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__60.MoveNext()
Feb 23 17:30:51 bundtbot bundtbot[12851]:         --- End of stack trace from previous location where exception was thrown ---
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at BundtBot.ClientWebSocketWrapper.<ReceiveAsync>d__16.MoveNext() in C:\Users\Bundt\Source\Repos\BundtBot\src\DiscordApiWrapper\Gateway\ClientWebSocketWrapper.cs:line 129
Feb 23 17:30:51 bundtbot bundtbot[12851]:         --- End of stack trace from previous location where exception was thrown ---
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at BundtBot.ClientWebSocketWrapper.<>c__DisplayClass13_0.<<StartReceiveLoop>b__0>d.MoveNext() in C:\Users\Bundt\Source\Repos\BundtBot\src\DiscordApiWrapper\Gateway\ClientWebSocketWrapper.cs:line 86
Feb 23 17:30:51 bundtbot bundtbot[12851]: 2017-02-23T17:30:51.3520150-06:00 [**ERROR**]ClientWebSocketWrapper:    InnerException1: $System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake.
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__69.MoveNext()
Feb 23 17:30:51 bundtbot bundtbot[12851]:         --- End of stack trace from previous location where exception was thrown ---
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Feb 23 17:30:51 bundtbot bundtbot[12851]:            at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__60.MoveNext()
Feb 23 17:30:51 bundtbot bundtbot[12851]: 2017-02-23T17:30:51.3532900-06:00 [Warning]  ClientWebSocketWrapper:    Waiting for 2 seconds, then restarting ReceiveLoop
Feb 23 17:30:53 bundtbot bundtbot[12851]: 2017-02-23T17:30:53.3521320-06:00 [Warning]  ClientWebSocketWrapper:    Doubled web socket restart wait time to 4 seconds
Feb 23 17:30:53 bundtbot bundtbot[12851]: 2017-02-23T17:30:53.3528960-06:00 [Warning]  ClientWebSocketWrapper:    Restarting ClientWebSocketWrapper ReceiveLoop.
Feb 23 17:30:53 bundtbot bundtbot[12851]: 2017-02-23T17:30:53.3538820-06:00 [Warning]  ClientWebSocketWrapper:    Exception caught in ClientWebSocketWrapper ReceiveLoop.
Feb 23 17:30:53 bundtbot bundtbot[12851]: 2017-02-23T17:30:53.3542010-06:00 [**ERROR**]ClientWebSocketWrapper:    System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake.